services:
  node-known:
    build: .
    ports: 
      - "8002:8000"
      - "10002:10000"
    command: ["./gossip", "-firstNode=true"]

  node-connect-1:
    build: .
    depends_on: ["node-known"]
    ports: 
      - "8003:8000"
      - "10003:10000"
    command: ["./gossip"]

  node-connect-2:
    build: .
    depends_on: ["node-known"]
    ports: 
      - "8004:8000"
      - "10004:10000"
    command: ["./gossip"]

  prometheus:
    image: "prom/prometheus"
